title = "CNCF Branding"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
baseURL = "https://cncf-branding.netlify.com"

[params]
description = "Colors and logos for the Cloud Native Computing Foundation and its open source projects"
fontAwesomeVersion = "5.3.1"
twitterhandle = "CloudNativeFdn"

[params.logos]
navbar = "img/other/cncf/horizontal/white/cncf-white.png"

[[params.fonts]]
name = "Noto Sans"
sizes = [300, 400, 600, 700]

[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"

[outputs]
home = ["HTML", "REDIRECTS"]

[[menu.main]]
name = "Style Guide"
url = "https://github.com/cncf/foundation/blob/master/style-guide.md"
weight = 1
